"""add version column to sandbox_accounts

Revision ID: 8b68b24c965f
Revises: 001
Create Date: 2026-02-24 09:15:25.227004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b68b24c965f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox_accounts', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_sandbox_daily_value_account_date', 'sandbox_daily_values', ['account_id', 'date'])
    op.create_unique_constraint('uq_sandbox_position_account_stock', 'sandbox_positions', ['account_id', 'stock_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sandbox_position_account_stock', 'sandbox_positions', type_='unique')
    op.drop_constraint('uq_sandbox_daily_value_account_date', 'sandbox_daily_values', type_='unique')
    op.drop_column('sandbox_accounts', 'version')
    # ### end Alembic commands ###
